import React from 'react'
import "../static/styleabout.css"

const About = () => {
    return (
        <div className="container" id="container">
            <section id="mission">
                <div >
                    <h1>About Us</h1>
                    <h2>What is Dance ?</h2>
                    Dance, the movement of the body in a rhythmic way, usually to music and within a given space, for the purpose of expressing an idea or emotion, releasing energy, or simply taking delight in the movement itself.
                    is a powerful impulse, but the art of dance is that impulse channeled by skillful performers into something that becomes intensely expressive and that may delight spectators who feel no wish to dance themselves. These two concepts of the art of dance—dance as a powerful impulse and dance as a skillfully choreographed art practiced largely by a professional few—are the two most important connecting ideas running through any consideration of the subject. In dance, the connection between the two concepts is stronger than in some other arts, and neither can exist without the other.
                    the above broad definition covers all forms of the art, philosophers and critics throughout history have suggested different definitions of dance that have amounted to little more than descriptions of the kind of dance with which each writer was most familiar. Thus, Aristotle s statement in the Poetics that dance is rhythmic movement whose purpose is “to represent men s characters as well as what they do and suffer” refers to the central role that dance played in classical Greek theatre, where the chorus through its movements reenacted the themes of the drama during lyric interludes.
                    Copeland and James Whiteside
                    Copeland and James Whiteside
                    English ballet master John Weaver, writing in 1721, argued on the other hand that “Dancing is an elegant, and regular movement, harmoniously composed of beautiful Attitudes, and contrasted graceful Posture of the Body, and parts thereof.” Weaver s description reflects very clearly the kind of dignified and courtly movement that characterized the ballet of his time, with its highly formalized aesthetics and lack of forceful emotion. The 19th-century French dance historian Gaston Vuillier also emphasized the qualities of grace, harmony, and beauty, distinguishing “true” dance from the supposedly crude and spontaneous movements of early man:truly universal definition of dance must, therefore, return to the fundamental principle that dance is an art form or activity that utilizes the body and the range of movement of which the body is capable. Unlike the movements performed in everyday living, dance movements are not directly related to work, travel, or survival. Dance may, of course, be made up of movements associated with these activities, as in the work dances common to many cultures, and it may even accompany such activities. But even in the most practical dances, movements that make up the dance are not reducible to those of straightforward labour; rather, they involve some extra qualities such as self-expression, aesthetic pleasure, and entertainment.
                    article discusses the techniques and components of dance as well as the aesthetic principles behind its appreciation as an art. Various types of dance are discussed with emphasis on their style and choreography. The history of dance in various regions is treated in a number of articles; see dance, African; music and dance, Oceanic; dance, Western; arts, Central Asian; arts, East Asian; arts, Islamic; dance, Native American; arts, South Asian; and arts, Southeast Asian. The interaction between dance and other art forms is discussed in folk dance.
                    <h2>Asian Dance</h2>
                    <p>All Indian classical dances are to varying degrees rooted in the Natyashastra and therefore share common features: for example, the mudras (hand positions), some body positions, leg movement and the inclusion of dramatic or expressive acting or abhinaya. Indian classical music provides accompaniment and dancers of nearly all the styles wear bells around their ankles to counterpoint and complement the percussion.</p>
                    There are now many regional varieties of Indian classical dance. Dances like "Odra Magadhi", which after decades-long debate, has been traced to present day Mithila, Odisha region's dance form of Odissi (Orissi), indicate influence of dances in cultural interactions between different regions.
                    The Punjab area overlapping India and Pakistan is the place of origin of Bhangra. It is widely known both as a style of music and a dance. It is mostly related to ancient harvest celebrations, love, patriotism or social issues. Its music is coordinated by a musical instrument called the 'Dhol'. Bhangra is not just music but a dance, a celebration of the harvest where people beat the dhol (drum), sing Boliyaan (lyrics) and dance. It developed further with the Vaisakhi festival of the Sikhs.
                    The dances of Sri Lanka include the devil dances (yakun natima), a carefully crafted ritual reaching far back into Sri Lanka's pre-Buddhist past that combines ancient "Ayurvedic" concepts of disease causation with psychological manipulation and combines many aspects including Sinhalese cosmology. Their influence can be seen on the classical dances of Sri Lanka.[45]
                     An Indonesian Balinese dancer
                    Indonesian dances reflect the richness and diversity of Indonesian ethnic groups and cultures. There are more than 1,300 ethnic groups in Indonesia, it can be seen from the cultural roots of the Austronesian and Melanesian peoples, and various cultural influences from Asia and the west. Dances in Indonesia originate from ritual movements and religious ceremonies, this kind of dance usually begins with rituals, such as war dances, shaman dances to cure or ward off disease, dances to call rain and other types of dances. With the acceptance of dharma religion in the 1st century in Indonesia, Hinduism and Buddhist rituals were celebrated in various artistic performances. Hindu epics such as the Ramayana, Mahabharata and also the Panji became the inspiration to be shown in a dance-drama called "Sendratari" resembling "ballet" in the western tradition. An elaborate and highly stylized dance method was invented and has survived to this day, especially on the islands of Java and Bali. The Javanese Wayang wong dance takes footage from the Ramayana or Mahabharata episodes, but this dance is very different from the Indian version, indonesian dances do not pay as much attention to the "mudras" as Indian dances: even more to show local forms. The sacred Javanese ritual dance Bedhaya is believed to date back to the Majapahit period in the 14th century or even earlier, this dance originated from ritual dances performed by virgin girls to worship Hindu Gods such as Shiva, Brahma, and Vishnu. In Bali, dance has become an integral part of the sacred Hindu Dharma rituals. Some experts believe that Balinese dance comes from an older dance tradition from Java. Reliefs from temples in East Java from the 14th century feature crowns and headdresses similar to the headdresses used in Balinese dance today. Islam began to spread to the Indonesian archipelago when indigenous dances and dharma dances were still popular. Artists and dancers still use styles from the previous era, replacing stories with more Islamic interpretations and clothing that is more closed according to Islamic teachings.[46]
                    The dances of the Middle East are usually the traditional forms of circle dancing which are modernized to an extent. They would include dabke, tamzara, Assyrian folk dance, Kurdish dance, Armenian dance and Turkish dance, among others.[47][48] All these forms of dances would usually involve participants engaging each other by holding hands or arms (depending on the style of the dance). They would make rhythmic moves with their legs and shoulders as they curve around the dance floor. The head of the dance would generally hold a cane or handkerchief.
                    <h2>Western dance </h2>
                    <p>Folk dances vary across Europe and may date back hundreds or thousands of years, but many have features in common such as group participation led by a caller, hand-holding or arm-linking between participants, and fixed musical forms known as caroles.[50] Some, such as the maypole dance are common to many nations, while others such as the céilidh and the polka are deeply-rooted in a single culture. Some European folk dances such as the square dance were brought to the New World and subsequently became part of American culture.</p>
                    classical ballet dancers perform a sequence of The Nutcracker, one of the best known works of classical dance.
                Buffalo Dance, 1894
                developed first in Italy and then in France from lavish court spectacles that combined music, drama, poetry, song, costumes and dance. Members of the court nobility took part as performers. During the reign of Louis XIV, himself a dancer, dance became more codified. Professional dancers began to take the place of court amateurs, and ballet masters were licensed by the French government. The first ballet dance academy was the Académie Royale de Danse (Royal Dance Academy), opened in Paris in 1661. Shortly thereafter, the first institutionalized ballet troupe, associated with the Academy, was formed; this troupe began as an all-male ensemble but by 1681 opened to include women as well.
                century concert dance brought an explosion of innovation in dance style characterized by an exploration of freer technique. Early pioneers of what became known as modern dance include Loie Fuller, Isadora Duncan, Mary Wigman and Ruth St. Denis. The relationship of music to dance serves as the basis for Eurhythmics, devised by Emile Jaques-Dalcroze, which was influential to the development of Modern dance and modern ballet through artists such as Marie Rambert. Eurythmy, developed by Rudolf Steiner and Marie Steiner-von Sivers, combines formal elements reminiscent of traditional dance with the new freer style, and introduced a complex new vocabulary to dance. In the 1920s, important founders of the new style such as Martha Graham and Doris Humphrey began their work. Since this time, a wide variety of dance styles have been developed; see Modern dance.
            American dance developed in everyday spaces, rather than in dance studios, schools or companies. Tap dance, disco, jazz dance, swing dance, hip hop dance, the lindy hop with its relationship to rock and roll music and rock and roll dance have had a global influence. Dance styles fusing classical ballet technique with African-American dance have also appeared in the 21st century, including Hiplet.[51]
            <p>Dance is central to Latin American social life and culture. Brazilian Samba, Argentinian tango, and Cuban salsa are internationally popular partner dances, and other national dances—merengue, cueca, plena, jarabe, joropo, marinera, cumbia, bachata and others—are important components of their respective countries' cultures.[52] Traditional Carnival festivals incorporate these and other dances in enormous celebrations.[53]</p>
            has played an important role in forging a collective identity among the many cultural and ethnic groups of Latin America.[54] Dance served to unite the many African, European, and indigenous peoples of the region.[52] Certain dance genres, such as capoeira, and body movements, especially the characteristic quebradas or pelvis swings, have been variously banned and celebrated throughout Latin American history.[54]
            <h2>Dancers </h2>
            <p>Professional dancers are usually employed on contract or for particular performances or productions. The professional life of a dancer is generally one of constantly changing work situations, strong competitive pressure and low pay. Consequently, professional dancers often must supplement their incomes to achieve financial stability. In the U.S. many professional dancers belong to unions (such as the American Guild of Musical Artists, Screen Actors Guild and Actors' Equity Association) that establish working conditions and minimum salaries for their members. Professional dancers must possess large amounts of athleticism. To lead a successful career, it is advantageous to be versatile in many styles of dance, have a strong technical background and to use other forms of physical training to remain fit and healthy</p>
            <h2>Teachers </h2>
            <p>Dance teachers typically focus on teaching dance performance, or coaching competitive dancers, or both. They typically have performance experience in the types of dance they teach or coach. For example, dancesport teachers and coaches are often tournament dancers or former dancesport performers. Dance teachers may be self-employed, or employed by dance schools or general education institutions with dance programs. Some work for university programs or other schools that are associated with professional classical dance (e.g., ballet) or modern dance companies. Others are employed by smaller, privately owned dance schools that offer dance training and performance coaching for various types of dance.</p>
            <h2>Competitions</h2>
            <p>A dance competition is an organized event in which contestants perform dances before a judge or judges for awards, and in some cases, monetary prizes. There are several major types of dance competitions, distinguished primarily by the style or styles of dances performed. Dance competitions are an excellent setting to build connections with industry leading faculty members, adjudicators, choreographers and other dancers from competing studios. A typical dance competition for younger pre-professional dancers can last anywhere between two to four days, depending whether it is a regional or national competition.</p>
            The purpose of dance competitions is to provide a fun and educative place for dancers and give them the opportunity to perform their choreographed routines from their current dance season onstage. Often times, competitions will take place in a professional setting or may vary to non-performance spaces, such as a high school theatre. The results of the dancers are then dictated by a credible panel of judges and are evaluated on their performance than given a score. As far as competitive categories go, most competitions base their categories according to the dance style, age, experience level and the number of dancers competing in the routine.[60] Major types of dance competitions include
            <h2>Health</h2>
            <h4>Footwear</h4>
            <p>In most forms of dance the foot is the source of movement, and in some cases require specific shoes to aid in the health, safety ability of the dancer, depending on the type of dance, the intensity of the movements, and the surface that will be danced on.</p>
            Dance footwear can be potentially both supportive and or restrictive to the movement of the dancer.[62] The effectiveness of the shoe is related to its ability to help the foot do something it is not intended to do, or to make easier a difficult movement. Such effects relate to health and safety because of the function of the equipment as unnatural to the bodies usual mobility.
            <h4>Ballet</h4>
            <p>Ballet is notable for the risks of injury due to the biomechanics of the ankle and the toes as the main support for the rest of the movements. With the pointe shoe, the design specifically brings all of the toes together to allow the toes to be stood on for longer periods of time.[63]</p>
            are accessories associated with pointe shoes that help to mitigate injury and soothe pain while dancing, including things such as toe pads, toe tape, and cushions
            <h4>Body Image</h4>
            <p>Dancers are publicly thought to be very preoccupied with their body image to fit a certain mold in the industry. Research indicates that dancers do have greater difficulty controlling their eating habits as a large quantity strive for the art-form's ideal body mass. Some dancers often resort to abusive tactics to maintain a certain image. Common scenarios include dancers abusing laxatives for weight control and end up falling into unhealthy eating disorders. Studies show that a large quantity of dancers use at least one method of weight control including over exercising and food restriction. The pressure for dancers to maintain a below average weight affects their eating and weight controlling behaviours and their life-style.[65] Due to its artistic nature, dancers tend to have many hostile self-critical tendencies. Commonly seen in performers, it is likely that a variety of individuals may be resistant to concepts of self-compassion</p>
            <h4>Eating Disorders</h4>
            <p>Eating disorders in dancers are generally very publicly common. Through data analysis and studies published, sufficient data regarding the percentage and accuracy dancers have of realistically falling into unhealthy disordered eating habits or the development of an eating disorder were extracted. Dancers, in general, have a higher risk of suffering from eating disorders than the general public, primarily falling into anorexia nervosa and EDNOS. Research has yet to distinguish a direct correlation regarding dancers having a higher risk of suffering from bulimia nervosa. Studies concluded that dancers overall have a three times higher risk of suffering from eating disorders, more specifically anorexia nervosa and EDNOS.</p>
            <h2>Benefits </h2>
            <p>Dance is an art that refers to the movement of part of the body, some of the parts or the whole body, while keeping rhythmical to music (Luetzner). It is also referred to as a nonverbal form of communication as such movements can carry some massage. So that you see the benefits of dancing, this essay explores its importance in the human experience.</p>
            <h4>Expression</h4>
            <p>Dance as an art itself can be used to make expressions. The expressions can be either of joy, sorrow, warning or sometimes used for entertainment (Luetzner). In many parts of the world, dance can also be used to express talent or extra ordinary ability over others has in dance competitions.</p>
            <h4>Sense of unity</h4>
            <p>Dancing can be used as a symbol of unit. Among the several symbols of unity in different people in the world, such as taboos, cultures, songs, color and many others, dance is the most common way of expressing the sense of unity (Browning). In other words, dancing to a rhythm shows appreciation and acceptance despite the perspectives on can have.</p>
            <h4>Form of Exercise</h4>
            <p>This is because of the movements that are involved in dancing. It is proven that dancing can considerably improve one health by reducing the risk of some worse health conditions such as high blood pressure, weight gain and heart diseases (Browning). Just like any other exercise or sport, dancing has been incorporated in sports such as gymnastics, martial arts and figure skating (Luetzner).</p>
            Mental and Physical Relaxation. A combination of music and a simple physical exercise are the most effectual way of setting one s mind stress free. Dancing provides a quick and fun state that naturally relieves stress.
            <h4>Form of Entertainment</h4>
            <p>Dancing and fun go hand in hand thus; it is the easiest way to happiness. Happiness can come from the activities one gets involves into will in dance groups, which include, making friends, dancing settings and of course learning new dance styles (Luetzner).</p>
            <h4>Source of Motivation and Inspiration</h4>
            <p>This is commonly in some games, competition and even sports such as basketball and football. The dancers can perform before, during the event and even on commercial breaks to keep both the fans and the participants motivated.</p>
            <h4>Source of Income</h4>
            <p>Dancing is a skill that if specialize can lead into career. So many professional dancers nowadays are able to form affiliates and make a living from training interested people and competitions (Browning).</p>
            <h4>Enhances education</h4>
            <p>Dancing is a major booster for both the old and the young. In children, dancing contributes a lot in terms of personal improvement hence enhancing their skills more so those necessary for better education. Research shows that dancing help in boosting self-esteem as well as confidence (Luetzner).</p>
            <h4>Social and political activity</h4>
            <p>Just like any other practice, dancing is also a social and political activity. The importance of dance is vividly understood during performance. As explained above, dance sends a message to the audience hence it is an important activity to the society at large.</p>
            <h4>Confidence Booster</h4>
            <p>Dancing being an exercise, it improves posture, strengthen muscles and bring out sense of them. Eventually, this state of body and mind eliminates doubts and fears and replaces them with confidence and thus good time (Luetzner).</p>
            <h4>Enhances Creativity</h4>
            <p>Lastly, dance provides emotional outlet that helps a person to clearly reveal his or her feelings through coordinating body movement with music. It is this ability that translates back to the sense of creativity in the real world (Browning).</p>
        </div>
</section >
</div>
  )
}

export default About
