import React from 'react'
const ClassInfo = () => {
  return (
    <div>
      <section id="mission">
    <div className="container" id="container">
        <h1>Class Details </h1>
        <h2>Class Will Run 3 days in a Week.</h2>
        <h2>Batch 1</h2>
        <h4>Monday Wednesday Friday </h4>
        <h4>Time - 7:00 AM </h4>
        ipsum dolor sit, amet consectetur adipisicing elit. Accusamus pariatur sint quo accusantium saepe exercitationem rerum consequuntur laudantium ut distinctio praesentium sequi veritatis ratione dignissimos facilis, corporis quas adipisci soluta dolorum maxime in, at quam ullam? Veritatis ipsam similique nemo minus porro quas, ab praesentium ipsa fugiat! Consectetur debitis iure nobis tempora iusto voluptate recusandae possimus harum molestias. Facilis, id magnam. Accusantium accusamus facere provident quae officia sequi, cum non at fugiat deleniti? Voluptatem repudiandae culpa quam nihil, odio amet natus animi nulla perferendis unde, illum excepturi sequi similique incidunt sit deserunt ea nesciunt ullam neque. Nulla pariatur voluptatem nostrum.
        ipsum dolor sit amet consectetur adipisicing elit. Officiis, voluptatem iure totam labore reprehenderit eos. Laudantium perferendis eaque itaque sed eligendi sit labore omnis et. Ipsum nihil molestiae ea maiores, consequatur consectetur libero deserunt repudiandae quidem autem voluptates officiis, possimus unde fugit laudantium dolore, dicta excepturi velit nobis saepe enim laborum voluptatum deleniti. Beatae voluptatum aut minus in quibusdam ipsum ducimus laboriosam magnam officia consectetur aliquid temporibus esse sunt velit adipisci magni, corrupti commodi dignissimos sint quae a eos blanditiis quas id. Facere reprehenderit dolorem quod nihil, nisi nostrum distinctio recusandae voluptatum dolorum perferendis. Vel aspernatur nam quod dolorum beatae neque consectetur, distinctio quos accusamus dicta nisi vitae, ullam ex! Dolores tempora ad, nemo eos vero corrupti. Nemo placeat illum laboriosam totam voluptate nisi corrupti, repellat consequatur veniam! Natus hic dolores itaque, omnis magni id nostrum mollitia quibusdam odio excepturi dignissimos ullam, pariatur voluptatem similique eos iusto ipsam repudiandae tenetur vel velit neque? Accusantium ipsa odit esse fugiat, molestias veniam voluptate, consequuntur quos perferendis quae necessitatibus ratione in debitis. Id aliquid error aspernatur ab, odio adipisci optio quisquam totam animi expedita maiores non iure laborum doloribus voluptas perspiciatis laudantium veniam? Quibusdam iste, error quaerat illum dolore ab itaque ullam aperiam.
        <h2>Batch 2</h2>
        <h4>Monday Wednesday Friday </h4>
        <h4>Time - 9:00 AM </h4>
        ipsum dolor sit amet, consectetur adipisicing elit. Tenetur libero reiciendis fugit expedita, dolor, labore vel nostrum deleniti sint optio placeat vitae odio. Et eveniet culpa, obcaecati nesciunt ea temporibus modi facilis natus, repellendus minima odit, molestias quisquam ad? Deserunt tempore magnam suscipit numquam totam consequuntur, harum quos, reprehenderit dolores incidunt aliquid ipsa? Ullam voluptas omnis voluptatibus consequatur nihil iure qui sit commodi quas iusto, sequi ad sapiente eligendi quos odio ipsum alias fugiat dignissimos est eius earum reiciendis hic? Nesciunt recusandae quis totam accusantium architecto minus mollitia, soluta magni doloribus, nemo fugiat. Reprehenderit dicta, totam laboriosam dolorum minima quod.
        ipsum dolor sit amet consectetur adipisicing elit. Doloremque quisquam est officiis alias qui quo quibusdam nulla, iste culpa quam quod voluptatibus eum necessitatibus enim exercitationem facilis veritatis sit amet modi. Animi error atque sed. Temporibus delectus nemo dolore quas iusto dicta, voluptas labore, totam aliquam voluptates unde ducimus voluptatum, veritatis eius perspiciatis mollitia reprehenderit optio reiciendis porro eos itaque aut quae eum. Alias error maxime nemo fuga sapiente? Adipisci delectus possimus aut sapiente totam suscipit molestias praesentium neque ipsa dignissimos mollitia, nulla aperiam cumque soluta esse reprehenderit facere cum sequi! Totam repudiandae dignissimos consequatur aspernatur esse provident tenetur ullam nemo quos obcaecati cumque natus expedita architecto, sit harum iusto ut? Eius quia dignissimos, iusto est dolores, eos atque voluptatibus ipsa pariatur at veritatis incidunt! Ullam omnis magnam alias quia quod deleniti aliquam voluptate! Deleniti dicta, adipisci optio animi inventore dolor doloremque sint. Numquam sed assumenda consectetur, quibusdam error impedit culpa? Modi quae iste cupiditate dignissimos commodi. Natus vel voluptate totam dolorem illum incidunt illo maxime quasi assumenda autem quia architecto, saepe nobis modi necessitatibus at nostrum corporis quas, libero dolores, quae ab! Nobis quibusdam tenetur sit iusto, id pariatur. Quibusdam eius tenetur deserunt voluptate earum reiciendis, tempora omnis cum!
        <h2>Batch 3</h2>
        <h4>Monday Wednesday Friday </h4>
        <h4>Time - 11:00 AM </h4>
        ipsum dolor sit amet consectetur adipisicing elit. Ipsam tempora ratione minima iure reprehenderit, exercitationem minus, praesentium a voluptatibus facere est amet aliquid inventore incidunt voluptate debitis optio sequi nihil. Ex dolore deleniti voluptates, possimus, tempore laborum repellat distinctio nostrum vel omnis magni odio eius, voluptate illo. Earum, ipsam neque. Sunt ut, commodi, nesciunt sint nostrum quo necessitatibus dolor repudiandae ad officia cumque recusandae ipsa voluptatum deserunt qui reprehenderit maiores mollitia. Porro veniam ratione perferendis nulla provident maxime, iste dolor dolorem numquam excepturi nesciunt veritatis sint error laboriosam velit vero debitis sed beatae atque adipisci reprehenderit repellat! Laudantium, dolorem cum?
        ipsum dolor sit, amet consectetur adipisicing elit. Ducimus praesentium vero adipisci sequi, nihil ad officia impedit quo architecto laudantium laboriosam dolorum omnis veniam, magni et dicta deserunt nesciunt doloribus consectetur. Nulla maiores reiciendis molestiae voluptatibus nisi rem minus quis praesentium temporibus! Porro harum nesciunt similique modi reprehenderit adipisci ducimus illo commodi cumque! Tempore voluptatem itaque repellendus iure accusantium numquam. Praesentium distinctio dolorem reprehenderit quibusdam nostrum, minus molestias ratione repudiandae, est rerum ab explicabo, excepturi quo veritatis debitis cumque ducimus aut officia laborum eligendi quos accusantium eveniet obcaecati quas! At vel esse optio. Explicabo officiis dolorem ea consectetur dolor consequatur iusto earum, maiores nemo repellat, voluptates maxime, distinctio voluptas recusandae quis numquam suscipit a quaerat cupiditate id porro. Necessitatibus obcaecati doloribus sequi ducimus iusto aliquid quia voluptates tenetur corrupti quo fugiat, corporis laborum? Voluptatem ipsa dolorum quidem sequi quod odio culpa ducimus suscipit, id assumenda? Incidunt culpa porro ipsam dolorem provident modi suscipit, est sed odio. Excepturi et repellendus deserunt illum ipsum ut neque quis beatae molestiae, nemo quia totam assumenda hic? Repellendus aut libero provident dolorum a esse, reiciendis explicabo quos autem aperiam labore nesciunt repudiandae debitis atque excepturi exercitationem blanditiis, laboriosam placeat, ullam modi minima dolores quo recusandae?
        <h2>Batch 4</h2>
        <h4>Monday Wednesday Friday </h4>
        <h4>Time - 4:00 PM </h4>
        ipsum dolor sit amet, consectetur adipisicing elit. Magni libero perspiciatis odit quisquam facere, cupiditate, suscipit soluta, deserunt obcaecati minima doloremque optio reiciendis? Quam facilis consequatur dolore alias doloribus. Nulla, repellendus! Vero est repellendus vitae cupiditate laboriosam totam, repellat perferendis quia dolores? Aliquam deserunt atque quidem placeat at porro non, adipisci modi assumenda corporis architecto natus expedita, dicta praesentium. In dignissimos hic eaque sequi et libero, iure veritatis accusamus exercitationem tempore adipisci expedita similique voluptatem? Nemo, molestiae ut animi nulla possimus eius labore enim praesentium est rerum nihil tempora maxime perspiciatis velit reiciendis eos quisquam fugiat quaerat ex porro dolorem?
        ipsum dolor sit amet, consectetur adipisicing elit. Placeat minus ad doloribus mollitia est magnam amet repellat voluptatibus harum modi obcaecati quos iure nemo omnis aliquam accusamus ipsam natus, adipisci excepturi, voluptates dolor! Non quisquam delectus et totam possimus quia, quam rerum repudiandae voluptas praesentium molestias alias sapiente distinctio maiores vitae eos officiis nihil asperiores fugit unde soluta aperiam. Amet mollitia harum aut dignissimos perspiciatis, aliquam magnam cumque earum porro placeat odio culpa in provident omnis quia sit commodi maxime doloremque, cupiditate ipsam exercitationem veritatis veniam sint. Reprehenderit, maxime dolor aperiam sed illum minus reiciendis quaerat error possimus alias nobis, modi sit. Ipsa, expedita reprehenderit molestias natus in voluptatibus ea aliquam illo quidem non assumenda commodi error corrupti quisquam nisi cupiditate aperiam perferendis fuga ipsam cum quae provident similique ipsum totam? Ratione debitis perferendis architecto! Assumenda ullam cumque qui, recusandae sunt impedit quisquam pariatur non cupiditate architecto porro nostrum? Tempore dicta vel quia alias illum autem, consectetur cum, hic quaerat pariatur maiores modi commodi voluptatibus dolor porro totam eos iusto ex! Ea fugit officia provident repellendus rerum maiores maxime cumque possimus enim velit laudantium eaque, ipsa excepturi odit molestiae omnis? Non dolor repellendus saepe excepturi, debitis laboriosam repudiandae officia enim?
        <h2>Batch 5</h2>
        <h4>Monday Wednesday Friday </h4>
        <h4>Time - 6:00 PM </h4>
        ipsum dolor sit amet consectetur adipisicing elit. Ut eaque esse est pariatur dolores qui voluptates laborum! Et, laudantium ab doloribus nostrum deserunt soluta dignissimos labore cum odit repellat quisquam, aspernatur quae quaerat amet ipsa similique quos laboriosam nesciunt ut necessitatibus facilis? Quo adipisci sit velit tempora commodi, voluptatum perspiciatis amet vero delectus nesciunt unde fugiat natus cum hic reiciendis quia corporis, laborum similique a optio non quisquam. Ea unde quidem labore facilis accusantium explicabo assumenda molestiae cupiditate maiores, eveniet cum aspernatur voluptas placeat ipsum quis, itaque sed animi, error architecto qui totam recusandae nam voluptate? Dolores alias architecto facere.
        ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus magni, natus nostrum placeat sunt, at voluptatem doloribus nobis eveniet quibusdam exercitationem itaque aliquid. Dolores possimus illo consequuntur, ex libero deserunt enim molestiae dignissimos? Necessitatibus est deserunt explicabo velit. Eveniet optio harum iure praesentium suscipit pariatur nisi nemo, repellendus temporibus at voluptates ipsa maxime delectus cumque nam explicabo eos modi ducimus unde eaque, id minima doloremque! Tempore consectetur delectus explicabo ut odio dicta harum modi ipsam illo obcaecati voluptates unde ducimus, optio neque molestias magnam, alias culpa architecto, cupiditate ipsa consequatur. Repellendus, reprehenderit. Sed illum veniam fuga autem dolores, unde beatae voluptatibus provident rerum dicta reiciendis doloribus vel distinctio dolor eveniet minima, quaerat consectetur illo a! Eos modi blanditiis veniam dolor odio culpa expedita. Numquam ipsa nulla animi nemo optio! Provident optio, harum quis mollitia odit accusantium veniam labore minima ducimus ipsum dicta saepe. Magni, sunt commodi magnam iusto autem optio est dignissimos ipsa nemo tenetur libero mollitia asperiores. Aliquid animi iusto provident! Facilis eos provident atque. Culpa quas in quis cumque fuga maxime molestiae consequatur hic similique non accusamus, magni debitis totam saepe asperiores nulla ducimus assumenda temporibus fugit tenetur pariatur. Atque ut voluptatem ab at corporis inventore perferendis unde?
        <h2>Batch 6</h2>
        <h4>Tuesday Thrusday Saturday </h4>
        <h4>Time - 7:00 AM </h4>
        ipsum dolor sit amet consectetur adipisicing elit. Perferendis voluptate quae a inventore excepturi esse nemo aspernatur beatae iusto molestiae tempore temporibus provident cumque dolorem doloremque eum, itaque quis perspiciatis quaerat enim exercitationem, sequi ullam quas? Doloremque enim non sequi adipisci vel. Repudiandae vel sit beatae reiciendis cupiditate explicabo consequuntur error pariatur culpa, fuga veniam sequi illum expedita tempora delectus voluptas quae repellendus voluptatum assumenda itaque quidem corrupti dolorum. Repellendus fugit cupiditate fuga doloremque architecto accusantium iste amet pariatur hic quod, reiciendis incidunt neque? Explicabo voluptates ullam sequi eveniet, autem nobis at sit quis expedita harum repellendus in delectus sed!
        ipsum dolor sit, amet consectetur adipisicing elit. Et nostrum ab vero tenetur? Veniam iure blanditiis, ex velit ducimus incidunt? Esse explicabo deleniti deserunt repudiandae, doloremque cupiditate tempora perspiciatis libero? Tempore itaque id, facere facilis dolorem blanditiis tenetur et perferendis libero nobis nemo? In sapiente ipsa perferendis omnis reprehenderit consectetur! Velit aliquid tempora ipsa perferendis enim sequi laborum, maiores, impedit quo eius accusamus, dignissimos vero totam vel unde deleniti minus blanditiis consectetur! Tenetur modi labore itaque praesentium sit nostrum quidem. Et ipsum tempora similique, sit accusantium totam illo quidem? Repellendus, laborum quis. Veniam esse a inventore, rem aliquid excepturi expedita ipsam autem dolorum, laudantium omnis molestiae atque eaque. Necessitatibus architecto distinctio soluta dolor fuga sed modi aperiam qui eos quasi tempore, voluptas, fugit aut, expedita itaque amet quia. Ab eos iure ad ea aperiam. Earum quia ipsa mollitia facilis recusandae, vero alias libero voluptatem sit, officia nesciunt, nisi sapiente nemo expedita cupiditate eius totam aspernatur. Aspernatur fugiat cumque culpa explicabo excepturi eveniet iste, corrupti dolor soluta recusandae doloribus. Delectus optio maiores, repellendus, eius odit at officia consequatur aliquam nihil repudiandae cum quasi laborum minima voluptatem pariatur ex architecto! Quis, voluptas ab at optio animi dolore atque velit neque beatae eum.
        <h2>Batch 7</h2>
        <h4>Tuesday Thrusday Saturday </h4>
        <h4>Time - 9:00 AM </h4>
        ipsum dolor sit, amet consectetur adipisicing elit. Perspiciatis, nostrum. Debitis autem, consequuntur fugit ipsam inventore quos pariatur culpa, eligendi ea veritatis soluta fuga, eius omnis voluptatibus perspiciatis vel expedita! Neque iusto, autem laboriosam libero enim voluptates earum corporis reiciendis veniam consectetur quod beatae alias vitae dolorum! Aliquid voluptatibus veritatis illum fugit consectetur asperiores explicabo. Quis sunt numquam cumque ipsa et, optio debitis dolorum perferendis nulla? Delectus odit explicabo natus facilis, rerum porro dicta aut, rem nobis numquam ea laborum quam, ipsam excepturi et nulla repellendus. Soluta beatae hic animi, architecto vero quibusdam labore dolorum tenetur nemo ex, unde veniam?
        ipsum dolor sit amet consectetur adipisicing elit. Et consequuntur dolorum nobis animi autem nam suscipit praesentium, voluptatem rerum. Dolorum dignissimos minima voluptas eos, voluptatibus sit autem perspiciatis quibusdam beatae aliquam doloremque suscipit error alias deleniti ab et blanditiis nostrum tenetur modi officia fugiat accusantium? Consequatur voluptates sapiente nostrum asperiores beatae amet mollitia totam cupiditate sed, cumque fugit debitis, odit at corrupti! Mollitia id rem amet impedit eaque illo ut iure, est optio, sit libero nesciunt ex minus ipsam velit debitis esse delectus dolore alias cupiditate consequuntur deserunt sed! Sint iure vitae eius. Aspernatur quidem accusantium animi voluptatibus ab nulla similique. Optio repellendus nesciunt similique? Accusamus deleniti est excepturi voluptas, pariatur ab cumque ex quia officia aspernatur vero tenetur error praesentium blanditiis optio expedita labore voluptate illum. Praesentium libero placeat obcaecati dignissimos dolore commodi exercitationem laborum, vitae fugiat. Molestiae, tenetur. Quibusdam quam voluptatibus, voluptates optio commodi natus, velit rerum ipsam eos neque deleniti unde perferendis excepturi aliquam accusamus dolore, quos placeat ipsa quis qui? Neque veniam saepe quas fugiat repellendus, esse ipsum in maxime eos excepturi harum aperiam. Laboriosam dolor suscipit vero deserunt unde animi doloremque esse obcaecati laudantium iste quo praesentium beatae aliquam laborum magni, in facilis, ex dolorum.
        <h2>Batch 8</h2>
        <h4>Tuesday Thrusday Saturday </h4>
        <h4>Time - 11:00 AM </h4>
        ipsum dolor sit amet consectetur adipisicing elit. Eaque consequatur reprehenderit soluta, harum sed repellendus, assumenda nisi fugit sint voluptate, exercitationem eum nam vel velit modi iste? Modi, libero minus porro dignissimos nesciunt asperiores totam hic suscipit amet magnam ducimus quis maxime itaque explicabo facilis quam ullam sit perspiciatis? Adipisci ad nobis voluptatibus similique odio! Quas pariatur id adipisci deleniti quia, libero tenetur dolorum quae est incidunt, tempore necessitatibus accusantium harum consectetur. Ex excepturi soluta fuga, vitae velit animi alias magni rerum quaerat sint nobis atque quam impedit inventore quis fugiat? Minima atque beatae debitis modi aperiam quos autem sunt!
        ipsum dolor sit amet consectetur adipisicing elit. Ducimus explicabo, similique esse id, aspernatur ea voluptate magnam neque quas consequuntur quos necessitatibus cum at iste quaerat, rem autem quisquam doloribus a fugit alias sed voluptatem laborum minus? Possimus numquam, illum amet mollitia incidunt quis, optio quod asperiores porro inventore suscipit saepe distinctio minus excepturi ea dignissimos, explicabo voluptates quam atque? Quasi deleniti eius eveniet maxime ut accusantium temporibus. Rerum totam nulla at beatae aspernatur ipsa, similique, modi quae architecto nihil optio sint. A cumque qui fugiat labore tempora aut. Harum delectus corporis deleniti soluta obcaecati eveniet ad reiciendis, natus corrupti! Voluptatem error inventore fugit eveniet nulla officia quas id doloribus quod temporibus corrupti laudantium ipsam facilis fugiat dolor eos perferendis dolores, mollitia reprehenderit! Quibusdam tempore vel voluptatem recusandae saepe blanditiis tenetur numquam ipsum, corrupti nulla vero placeat est officiis aut sint sed ea adipisci optio, accusamus maiores. Nulla voluptatum esse velit rerum sed harum quaerat! Harum repellendus tenetur maiores, ratione cumque reprehenderit, aliquid, corporis molestiae ullam mollitia dolorem debitis ad. Cum voluptas minima inventore reprehenderit dolorum, natus consequuntur laborum maxime eius suscipit tempore modi dignissimos nulla doloribus quod debitis quaerat totam impedit obcaecati sint qui! Nemo reprehenderit hic obcaecati explicabo.
        <h2>Batch 9</h2>
        <h4>Tuesday Thrusday Saturday </h4>
        <h4>Time - 4:00 PM </h4>
        ipsum dolor sit amet, consectetur adipisicing elit. Accusamus mollitia voluptatibus dolor, pariatur optio, nobis accusantium ex unde aliquam suscipit error beatae, magni maxime iste? Quaerat earum aliquam nemo tempore at aperiam asperiores repellendus soluta fugiat porro pariatur, nam reprehenderit facere tenetur deserunt ex! Omnis modi nisi obcaecati mollitia commodi, reiciendis sit alias expedita nemo? Quia corporis, voluptas modi deserunt sint culpa iusto officia excepturi veritatis itaque error perspiciatis, dolore sed fugiat. Officia a ratione, itaque doloremque voluptatem alias similique nulla! Repellat, quod mollitia? Quod suscipit dolor repudiandae ad enim, fugiat, repellendus dolorem corrupti temporibus doloremque incidunt laborum aliquam facere!
        ipsum dolor sit amet consectetur adipisicing elit. Adipisci, quam dolore? Reprehenderit amet tenetur quos impedit. Quia fugit porro ad minus hic earum nihil voluptatem iure accusamus maiores obcaecati tenetur ullam harum quis ipsa quas cum dolorem eaque vel nostrum, tempore adipisci ratione? Quis, doloribus aperiam! Blanditiis dignissimos exercitationem sapiente odit molestias quam harum, suscipit nisi corporis ducimus sequi nemo at nulla quaerat culpa illo similique. Vero tempore quidem, atque corporis illo sed. Optio recusandae, ut beatae suscipit ratione cupiditate esse magnam culpa odit fuga in assumenda eum unde vitae eligendi, iusto soluta rem. Et suscipit est tempore, sequi iure omnis aperiam dolore provident officiis, corporis modi? Illum, repudiandae ipsam quidem obcaecati fugiat nam cupiditate voluptatibus nobis iure dignissimos delectus iusto eum sapiente ullam labore nesciunt commodi ipsum corporis. Libero, corporis dolor illum, quod quae laudantium ratione minima a deserunt autem voluptates tenetur officia ipsum distinctio consequatur. Fuga, culpa debitis, dolores tenetur architecto esse ipsa distinctio rem velit libero consectetur quas a deserunt vel. Totam sequi tempora numquam, animi illum aperiam corporis dolorum modi reiciendis deleniti unde iure repellendus sit ut doloribus sapiente ab excepturi, alias, quo impedit aliquam nisi dolorem quibusdam tenetur. Repellat sapiente officia error porro aliquid tempora.
        <h2>Batch 10</h2>
        <h4>Tuesday Thrusday Saturday </h4>
        <h4>Time - 6:00 PM </h4>
        ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam quasi doloremque explicabo cumque ex nisi? Quo ullam, nostrum quis qui in excepturi animi odio possimus nobis impedit quibusdam ipsum fugit blanditiis, fuga vel debitis unde eligendi. Deleniti similique iusto minus, quaerat natus aperiam ab nobis repellat enim perspiciatis ipsum quam accusantium nihil illo beatae alias doloremque ratione ad, fuga doloribus? Dolorem eum fugiat atque iure dolor, officiis eligendi ipsam minus ipsum in fugit ad quidem tempore, voluptatem blanditiis saepe quam reiciendis animi quisquam quas repellendus aliquid. Aut tempora in voluptas sequi, blanditiis, placeat amet ea, repellat beatae ipsam recusandae ad.
        ipsum dolor sit amet consectetur adipisicing elit. Doloremque, dolorum facere! Autem debitis architecto vero quod inventore eligendi quas dolorem, dolores ad soluta nihil. Neque voluptatem quis provident ullam dolorum temporibus accusamus harum vero at corrupti quod assumenda laudantium inventore recusandae ratione quidem quia dolores nesciunt eos corporis deserunt dolore ex, eveniet qui. Doloremque explicabo maxime laudantium modi accusantium voluptatibus dolorum voluptatum, magnam architecto aspernatur est quis doloribus molestias iure cumque, ad eligendi commodi, natus saepe ducimus? Ducimus quo culpa perspiciatis eius quam asperiores obcaecati distinctio, illum, dignissimos accusantium dolorum nisi blanditiis nobis unde quos animi praesentium omnis vitae. Earum ea corporis odit iure unde minima necessitatibus in illum quo modi facilis dicta fuga quis reprehenderit dolore sit nulla rerum, tenetur eum deleniti distinctio molestiae ab voluptas provident. Recusandae velit maiores voluptate ut minima ad ab rem, consequuntur eaque obcaecati eveniet optio laborum enim inventore quisquam sequi. Sint culpa quod quae voluptas nobis architecto est doloremque quisquam saepe omnis voluptatum rerum atque enim sed dolorum assumenda iusto, reprehenderit autem hic eligendi corrupti. Doloribus ad ipsum voluptatum dolores sunt eum voluptas veniam, asperiores voluptatibus, facilis delectus excepturi voluptatem reiciendis iusto minima reprehenderit. Nostrum vero accusantium rerum beatae, expedita non fuga doloribus!
        <h2>Your Batch and Timing will be inform in your gmail </h2>
        <h1>For any Quearies </h1>
        <h4>Phone-344 3434 2343</h4>
        <h4>Phone-344 3434 2753</h4>
        <h4>Phone-344 3434 2143</h4>
        <h4>Phone-344 3434 2373</h4>
        <h4>Phone-344 3434 2753</h4>
        <h4>Phone-344 3434 2233</h4>
    </div>
</section>
    </div>
  )
}

export default ClassInfo
